POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pY2tzVXNlck5hbWUiLCJpZCI6IjVmMmZlMTZhNWZjNDYzOTRlNmI1NDY1NSIsImlhdCI6MTU5NzIxMzg0M30.EAa2hAyQ-ACvSA1knC0-LoBR5k8KurueniPBGw7aFkY

{
    "title": "Nick's authenticated 7th blog post",
    "author": "Nick",
    "url": "thisIsTheUrl",
    "likes": 20
}